#!/bin/sh
. ~/.config/HyprV/hyprv.conf

#Check the version 
SETUP=$(readlink -f ~/.config/waybar/config.jsonc | cut -d '-' -f1 | cut -d '/' -f8)

# Check which waybar theme is set
THEMEIS=$(readlink -f ~/.config/waybar/style.css | cut -d '-' -f3)

#if the theme is not dark then we need to switch to it

get_setup() {
    SETUP=$(readlink -f ~/.config/waybar/config.jsonc | cut -d '-' -f1 | cut -d '/' -f8)
}

if [[ $THEMEIS == "light.css" ]]; then
    SWITCHTO="-dark"
    MODESTR="Dark"
else
    SWITCHTO="-light"
    MODESTR="Light"
fi

#show a message
notify-send -h string:x-canonical-private-synchronous:sys-notify -u low "switching to $MODESTR"

#set the waybar theme
ln -sf ~/.config/HyprV/waybar/style/$SETUP'-style'$SWITCHTO.css ~/.config/waybar/style.css

#set the wofi theme
ln -sf ~/.config/HyprV/wofi/style/$SETUP'-style'$SWITCHTO.css ~/.config/wofi/style.css

#set the mako theme
ln -sf ~/.config/HyprV/mako/conf/config$SWITCHTO ~/.config/mako/config

#set the measuring unit
if [[ $SET_MESU == "I" ]]; then
    ln -sf ~/.config/HyprV/waybar/conf/mesu-imp.jsonc ~/.config/HyprV/waybar/conf/mesu.jsonc
elif [[ $SET_MESU == "M" ]]; then
    ln -sf ~/.config/HyprV/waybar/conf/mesu-met.jsonc ~/.config/HyprV/waybar/conf/mesu.jsonc
fi

#set the xfce and GTK theme
if [[ $SWITCHTO == "-dark" ]]; then #check for light theme
    if [[ $SETUP == "setup1" ]]; then
            xfconf-query -c xsettings -p /Net/IconThemeName -s "BeautyLine" #icon theme
            gsettings set org.gnome.desktop.interface icon-theme "BeautyLine"
            xfconf-query -c xsettings -p /Net/ThemeName -s "Orchis-Purple-Dark" #theme switcher
            gsettings set org.gnome.desktop.interface gtk-theme "Orchis-Purple-Dark"
            gsettings set org.gnome.desktop.interface cursor-theme "capitaine-cursors"
        elif [[ $SETUP == "setup2" ]]; then
            xfconf-query -c xsettings -p /Net/IconThemeName -s "BeautyLine"
            gsettings set org.gnome.desktop.interface icon-theme "BeautyLine"
            xfconf-query -c xsettings -p /Net/ThemeName -s "Material-Black-Plum-3.36"
            gsettings set org.gnome.desktop.interface gtk-theme "Material-Black-Plum-3.36"
            gsettings set org.gnome.desktop.interface cursor-theme "capitaine-cursors"
        elif [[ $SETUP == "setup3" ]]; then
            xfconf-query -c xsettings -p /Net/IconThemeName -s "Material-Black-Blueberry-Suru-GLOW"
            gsettings set org.gnome.desktop.interface icon-theme "Material-Black-Blueberry-Suru-GLOW"
            xfconf-query -c xsettings -p /Net/ThemeName -s "Material-Black-Blueberry-3.36"
            gsettings set org.gnome.desktop.interface gtk-theme "Material-Black-Blueberry-3.36"
            gsettings set org.gnome.desktop.interface cursor-theme "capitaine-cursors"
        elif [[ $SETUP == "setup4" ]]; then
            xfconf-query -c xsettings -p /Net/IconThemeName -s "Material-Black-Cherry-Suru-GLOW" #icon theme
            gsettings set org.gnome.desktop.interface icon-theme "Material-Black-Cherry-Suru-GLOW"
            xfconf-query -c xsettings -p /Net/ThemeName -s "Material-Black-Cherry-3.36" #theme switcher
            gsettings set org.gnome.desktop.interface gtk-theme "Material-Black-Cherry-3.36"
            gsettings set org.gnome.desktop.interface cursor-theme "capitaine-cursors"
    fi
fi

# if [[ $SWITCHTO == "-dark" ]]; then #check for light theme
#     if [[ $SETUP == "setup4" && $SETUPTO == "setup1-" ]]; then
#             xfconf-query -c xsettings -p /Net/IconThemeName -s "BeautyLine" #icon theme
#             gsettings set org.gnome.desktop.interface icon-theme "BeautyLine"
#             xfconf-query -c xsettings -p /Net/ThemeName -s "Orchis-Purple-Dark" #theme switcher
#             gsettings set org.gnome.desktop.interface gtk-theme "Orchis-Purple-Dark"
#             gsettings set org.gnome.desktop.interface cursor-theme "Sweet-cursors"
#         elif [[ $SETUP == "setup1" && $SETUPTO == "setup2-" ]]; then
#             xfconf-query -c xsettings -p /Net/IconThemeName -s "BeautyLine"
#             gsettings set org.gnome.desktop.interface icon-theme "BeautyLine"
#             xfconf-query -c xsettings -p /Net/ThemeName -s "Material-Black-Plum-3.36"
#             gsettings set org.gnome.desktop.interface gtk-theme "Material-Black-Plum-3.36"
#             gsettings set org.gnome.desktop.interface cursor-theme "Breeze"
#         elif [[ $SETUP == "setup2" && $SETUPTO == "setup3-" ]]; then
#             xfconf-query -c xsettings -p /Net/IconThemeName -s "Material-Black-Blueberry-Suru-GLOW"
#             gsettings set org.gnome.desktop.interface icon-theme "Material-Black-Blueberry-Suru-GLOW"
#             xfconf-query -c xsettings -p /Net/ThemeName -s "Material-Black-Blueberry-3.36"
#             gsettings set org.gnome.desktop.interface gtk-theme "Material-Black-Blueberry-3.36"
#             gsettings set org.gnome.desktop.interface cursor-theme "Breeze"
#         elif [[ $SETUP == "setup3" && $SETUPTO == "setup4-" ]]; then
#             xfconf-query -c xsettings -p /Net/IconThemeName -s "Material-Black-Cherry-Suru-GLOW" #icon theme
#             gsettings set org.gnome.desktop.interface icon-theme "Material-Black-Cherry-Suru-GLOW"
#             xfconf-query -c xsettings -p /Net/ThemeName -s "Material-Black-Cherry-3.36" #theme switcher
#             gsettings set org.gnome.desktop.interface gtk-theme "Material-Black-Cherry-3.36"
#             gsettings set org.gnome.desktop.interface cursor-theme "Sweet-cursors"
#     fi
# fi



if [[ $SWITCHTO == "-light" ]]; then #check for light theme
    if [[ $SETUP == "setup1" ]]; then
        xfconf-query -c xsettings -p /Net/IconThemeName -s "BeautyLine"
        gsettings set org.gnome.desktop.interface icon-theme "BeautyLine"
        xfconf-query -c xsettings -p /Net/ThemeName -s "Orchis-Pink"
        gsettings set org.gnome.desktop.interface gtk-theme "Orchis-Pink"
        gsettings set org.gnome.desktop.interface cursor-theme "capitaine-cursors-light"
    elif [[ $SETUP == "setup2" ]]; then
        xfconf-query -c xsettings -p /Net/IconThemeName -s "BeautyLine"
        gsettings set org.gnome.desktop.interface icon-theme "BeautyLine"
        xfconf-query -c xsettings -p /Net/ThemeName -s "Orchis-Purple"
        gsettings set org.gnome.desktop.interface gtk-theme "Orchis-Purple"
        gsettings set org.gnome.desktop.interface cursor-theme "capitaine-cursors-light"
    elif [[ $SETUP == "setup3" ]]; then
        xfconf-query -c xsettings -p /Net/IconThemeName -s "We10X-special"
        gsettings set org.gnome.desktop.interface icon-theme "We10X-special"
        xfconf-query -c xsettings -p /Net/ThemeName -s "Orchis"
        gsettings set org.gnome.desktop.interface gtk-theme "Orchis"
        gsettings set org.gnome.desktop.interface cursor-theme "capitaine-cursors-light"
    elif [[ $SETUP == "setup4" ]]; then
        xfconf-query -c xsettings -p /Net/IconThemeName -s "We10X-red" #icon theme
        gsettings set org.gnome.desktop.interface icon-theme "We10X-red"
        xfconf-query -c xsettings -p /Net/ThemeName -s "Orchis-Red-Light" #theme switcher
        gsettings set org.gnome.desktop.interface gtk-theme "Orchis-Red-Light"
        gsettings set org.gnome.desktop.interface cursor-theme "capitaine-cursors-light"
    fi
fi

#xfconf-query -c xsettings -p /Net/ThemeName -s "Adwaita$SWITCHTO"
#gsettings set org.gnome.desktop.interface gtk-theme "Adwaita$SWITCHTO"


#change the background image and be cool about it ;)
if [ -z $SET_BG ]; then
    swww img ~/.config/HyprV/backgrounds/$SETUP'-background'$SWITCHTO.jpg --transition-fps 60 --transition-type wipe --transition-duration 2
else
    swww img $SET_BG --transition-fps 60 --transition-type wipe --transition-duration 2
fi

#update the lightdm image
cp -f ~/.config/HyprV/backgrounds/$SETUP'-background'$SWITCHTO.jpg /etc/lightdm/backgrounds/wallpaper.jpg

#reset mako
sleep 1
pkill mako
mako &

#restart the waybar
#killall -SIGUSR2 waybar <-- start causing web brwsers to close so switched to below...
pkill waybar
waybar &

if [[ $SETUP == "setup4" ]]; then
    waybar --config ~/.config/HyprV/waybar/conf/setup4-config-bottom.jsonc
fi
